# Generated by Django 5.1.7 on 2025-04-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='course',
            new_name='paid_course',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='lesson',
            new_name='paid_lesson',
        ),
    ]
